spring:
  application:
    name: spring-security-jwt
  datasource:
    url: jdbc:mysql://localhost:3306/spring_security_oauth2
    username: nikola
    password: Natalija_21?
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect


server:
  port: 8000
  error:
    include-message: always

rsa:
  private-key: classpath:certs/private-keyy.pem
  public-key: classpath:certs/public-key.pem

logging:
  level:
    org:
      springframework: INFO